### PR TITLE
Parametrized message length

### PR DESCRIPTION
**Pull request by ilyaukin**
Hi,
this parametrizes max message length (actually web skype accepts up to 32000 characters)

### CODE REVIEW

**Comment by sdimkov** [comment]
@ilyaukin Thanks for putting together a PR.

The max message length is something internal to the implementation of SkypeWeb and this adapter. I'm not sure why should it be exposed to an end-user as a config option.

Could you explain the motivation behind these changes ?

**Comment by ilyaukin** [comment]
HI Stoyan,

I needed longer messages to avoid message splitting and shuffling parts. Parameter is because  maximum length which is accepted by Skype can depend on network etc., so exact limit might not be known in advance.

**Comment by sdimkov** [comment]
> to avoid message splitting and shuffling parts

Are sure you experienced this? Because that's a real problem and a parameter wouldn't really solve it.
Can you reproduce the situation at which the adapter shuffles the order of messages?

I would like few changes applied before merging this:
- Parse the ENV only once in the constructor. 
- Ensure provided value is valid (ex. between 100 and 30000)
- Log that non-default value is provided

**Comment by ilyaukin** [comment]
Yes, I experienced that. I think that is not the adapter shuffles messages, that skype server does not guarantee messages order. Updated pull request.

**Comment by sdimkov** [comment]
Thanks! merged.

If you're able to reproduce the shuffling - you may try delaying consecutive requests (in the sendRequest() method).

**Comment by sdimkov** [comment]
Released in v0.9.12

**Pull request merged**
